arch: ViT
in_shape: [1, 140, 140, 2350]
out_channels: 6
patch_shape: [14, 14, 50]
hidden_dim: 240
depth: 2
mask_frac: 0.
num_heads: 4
mlp_ratio: 2.0
attn_drop: 0.
proj_drop: 0.
mlp_drop: 0.25
learn_pos_encoding: True
out_act: sigmoid
out_mlp: True
checkpoint_grads: False
