arch: ViT
in_shape: [1, 140, 140, 2350]
out_channels: 6
# patch_shape: [7, 7, 94]
patch_shape: [7, 7, 47]
condition_dim: 46
hidden_dim: 256
depth: 4
num_heads: 4
mlp_ratio: 2.0
attn_drop: 0.
proj_drop: 0.
learn_pos_encoding: True
# final_conv: False
# final_conv_channels: None
long_skips: False
out_act: sigmoid