arch: ViT
in_shape: [1, 140, 140, 2350]
out_channels: 6
in_conv: False
patch_shape: [7, 7, 47]
mask_frac: 0.
# multiple of 6
hidden_dim: 240
depth: 4
num_heads: 6
mlp_ratio: 2.0
attn_drop: 0.
proj_drop: 0.
mlp_drop: 0.25
learn_pos_encoding: True
long_skips: False
out_act: sigmoid
out_mlp: True
checkpoint_grads: False
