arch: ViT
in_shape: [1, 28, 28, 470]
out_channels: 6
in_conv: False
patch_shape: [4, 4, 5]
hidden_dim: 240 # must be divisible by 4 and 6
depth: 2
mask_frac: 0.
num_heads: 4
mlp_ratio: 2.0
attn_drop: 0.
proj_drop: 0.
mlp_drop: 0.25
learn_pos_encoding: True
out_act: sigmoid
out_mlp: True
checkpoint_grads: False