arch: ViT
in_shape: [1, 28, 28, 470]
out_channels: 6
in_conv: False
conv:
  in_channels: 1
  hidden_channels: 16
  xstride: 3
  zstride: 55
  zpadding: 1
patch_shape: [4, 4, 5]
hidden_dim: 240
depth: 2
mask_frac: 0.
num_heads: 4
mlp_ratio: 2.0
attn_drop: 0.
proj_drop: 0.
mlp_drop: 0.25
learn_pos_encoding: True
out_act: sigmoid
out_mlp: True
checkpoint_grads: False