arch: ViT
in_shape: [1, 70, 70, 1175]
out_channels: 6
# patch_shape: [7, 7, 47] # 10 x 10 x 25 = 2500 tokens with 7x7x47 = 2300 voxels
patch_shape: [7, 7, 25] # 10 x 10 x 45 = 4500 tokens with 7x7x47 = 1225 voxels
mask_frac: 0.
hidden_dim: 240
depth: 2
num_heads: 4
mlp_ratio: 2.0
attn_drop: 0.
proj_drop: 0.
mlp_drop: 0.
learn_pos_encoding: True
out_act: sigmoid
checkpoint_grads: False