x:
  - {_target_: src.utils.transforms.AddSingletonChannel}
  - {
    _target_: src.utils.transforms.Center,
    lo: -120.,
    hi: -1.
  }
  
y:
  - {
    _target_: src.utils.transforms.Center,
    lo: [0.55, 0.20, 100., 38., 4.0, 10.6],
    hi: [10.0, 0.40, 1500., 42., 5.3, 250.],
    indices: "${target_indices}"
  }
