run_name: classification_mini_${net.arch}
experiment: ClassificationExperiment

data:
  dir0: /remote/gpu02/ore/data/x2
  dir1: /remote/gpu02/ore/data_new/x2
  file_by_file: True
  
net:
  out_channels: 1

defaults:
  - default
  - preprocessing: xonly
  - net: cnn_mini
  - _self_