run_name: dummy
experiment: DummyExperiment
train: True
evaluate: True
plot: True

dtype: float32
use_gpu: True
device: 0
submit: False
dry_run: False

data:
  splits: {train: 0.5, val: 0.2, test: 0.3}
  on_gpu: False

training:
  epochs: 1
  lr: 1.e-4
  batch_size: 500
  use_scheduler: False
  gradient_norm: null
  adam:
    betas: [0.99, 0.999]
    weight_decay: 1.e-3

  validate_freq: 1
  save_freq: null
  start_epoch: null
  use_tensorboard: True
  
preprocessing:

defaults:
  - cluster: pbs
  - net: cnn
  # - preprocessing
  # - schedule ?
  - hydra
  - _self_