run_name: ???
experiment: ???
train: True
evaluate: True
plot: True

proj_dir: /remote/gpu02/ore/skatr
dtype: float32
use_gpu: True
num_cpus: 2
device: 0
submit: False
dry_run: False

prev_exp_dir: null

data:
  dir: /scratch2/heneka/21cmlightcones/pure_simulations/
  splits:
    train: 0.75
    test: 0.15
  sequential_splits: False
  on_gpu: False
  file_by_file: True

training:
  epochs: 1
  lr: 1.e-3
  batch_size: 32
  test_batch_size: 200
  optimizer:
    name: AdamW
    kwargs: {weight_decay: 1.e-3}
  scheduler: {}
  augment: True
  augmentations:
    RotateAndReflect: {include_identity: True}
  gradient_norm: null
  validate_freq: 1
  patience: null
  save_best_epoch: True
  save_freq: null
  warm_start: null
  warm_start_epoch: null
  use_tensorboard: True
  
backbone: null
frozen_backbone: True

defaults:
  - cluster: pbs
  - hydra
  - _self_