run_name: ???
experiment:
  _target_: ???
train: True
evaluate: True
plot: True

use_gpu: True
num_cpus: 0
device: 0
use_tf32: True
use_amp: False
submit: False
dry_run: False

prev_exp_dir: null

data:
  dir: ???
  val_frac: 0.10
  test_frac: 0.15
  sequential_splits: False
  on_gpu: False
  num_workers: 0
  use_test_dir: False
  summarize: False
  summary_batch_size: 150

training:
  epochs: 1
  lr: 1.e-3
  batch_size: 32
  test_batch_size: 200
  optimizer:
    _target_: torch.optim.AdamW
    weight_decay: 1.e-3
  use_amp: False
  scheduler: {}
  augment: True
  augmentations:
    RotateAndReflect: {include_identity: True}
  augment_test: False
  gradient_norm: null
  validate_freq: 1
  patience: null
  save_best_epoch: True
  save_freq: null
  log_iters: 50
  warm_start: null
  warm_start_epoch: null
  use_tensorboard: True
  
summary_net: null

defaults:
  - cluster: pbs
  - hydra
  - _self_