run_name: fine_regression_micro_${net.arch}
experiment: RegressionExperiment

backbone: runs/pretraining_micro/2024-06-06_22-41-11 # best: ema + adam + norm + l2
latent_dim: 128

training:
  epochs: 100

net:
  units:
  - ${latent_dim}
  - ${latent_dim}
  - 6
  out_act: sigmoid

data:
  dir: /scratch/ore/data/x5
  file_by_file: False
  
defaults:
  - default
  - preprocessing: xandy
  - net: mlp
  - _self_