run_name: fine_regression_micro_${net.arch}
experiment: RegressionExperiment

backbone: runs/pretraining_micro/2024-07-04_18-06-14
latent_dim: 144

training:
  lr: 1.e-3
  epochs: 500

net:
  units:
  - ${latent_dim}
  - ${latent_dim}
  - 6
  out_act: sigmoid
  
defaults:
  - regression_micro
  - override net: mlp
  - _self_