run_name: fine_regression_micro_${net.arch}
experiment: RegressionExperiment

backbone: runs/pretraining_micro:latent200:pred128/2024-06-03_16-22-39
net:
  units: [128, 256, 256, 6] # input dim must match backbone embedding dim
  out_act: sigmoid

data:
  dir: /remote/gpu01a/heneka/21cmlightcones/pure_simulations/x5
  file_by_file: True

preprocessing:
  AddSingletonChannel: {}
  Center: {}

training:
  epochs: 150
  lr: 1.e-3
  batch_size: 64
  optimizer:
    name: AdamW
    kwargs: {weight_decay: 1.e-3}
  
defaults:
  - default
  - net: mlp
  - _self_