run_name: fine_regression_${net.arch}
experiment: RegressionExperiment

# backbone: runs/pretraining_micro/huge_775
# latent_dim: 360
backbone: runs/pretraining_micro/2024-07-23_15-01-12
latent_dim: 144
adapt_res: True

num_cpus: 4

data:
  summarize: True
  summary_batch_size: 5

training:
  lr: 5.e-4
  epochs: 500

net:
  units:
  - ${latent_dim}
  - ${latent_dim}
  - 6
  out_act: sigmoid
  
defaults:
  - regression
  - override net: mlp
  - _self_