run_name: fine_regression_micro_${net.arch}
experiment: RegressionExperiment

backbone: runs/siam_micro_sym:True_mask:True_norm:True/2024-05-29_17-56-36
net:
  units: [128, 256, 256, 6] # input dim must match backbone embedding dim
  out_act: sigmoid

data:
  dir: /remote/gpu01a/heneka/21cmlightcones/pure_simulations/x5
  file_by_file: True

preprocessing:
  AddSingletonChannel: {}
  Center: {}
  
defaults:
  - default
  - net: mlp
  - _self_