run_name: fine_regression_micro_${net.arch}:block_mask
experiment: RegressionExperiment

backbone: runs/pretraining_micro:block_mask/2024-06-18_16-09-59
latent_dim: 128

net:
  units:
  - ${latent_dim}
  - 256
  - 256
  - 6
  drop: 0.25
  out_act: sigmoid

data:
  # not stored in gpu:
  #dir: /remote/gpu01a/heneka/21cmlightcones/pure_simulations/x5
  # stored gpu02:
  dir: /scratch/ore/data/x5
  file_by_file: False

training:
  epochs: 200
  lr: 1.e-3
  batch_size: 64
  optimizer:
    name: AdamW
    kwargs: {weight_decay: 1.e-3}
  
defaults:
  - default
  - preprocessing: xandy
  - net: mlp
  - _self_