run_name: fine_reg_hires_interp
experiment: RegressionExperiment

backbone: runs/pretraining_micro/2024-07-23_15-01-12
latent_dim: 144
adapt_res: True

num_cpus: 4

data:
  dtype: float16
  summarize: True
  summary_batch_size: 24

training:
  dtype: float32
  lr: 5.e-4
  epochs: 500

net:
  units:
  - ${latent_dim}
  - ${latent_dim}
  - 6
  out_act: sigmoid
  
defaults:
  - regression
  - override net: mlp
  - _self_