run_name: fine_regression_mini_${net.arch}
experiment: RegressionExperiment

backbone: /remote/gpu00/nordmann/skatr/runs/pretraining_mini/2024-07-15_10-09-39
latent_dim: 144

net:
  units:
  - ${latent_dim}
  - ${latent_dim}
  - 6
  out_act: sigmoid

data:
  #dir: /remote/jerry/nordmann/data_new/x2
  #dir: /scratch/ore/data_new/x2
  dir: /scratch/nordmann/data_new/x2
  #dir: /remote/gpu01a/heneka/21cmlightcones/opt_simulations/x2
  file_by_file: True
  sequential_splits: True
  splits: {train: 0.75, val: 0.1, test: 0.15}

cluster:
  queue: h100
  node: 1

training:
  epochs: 120
  batch_size: 64
save_best_epoch: True

freeze_backbone: True
  
defaults:
  - default
  - preprocessing: xandy_new
  - net: mlp
  - _self_