run_name: fine_new
experiment: RegressionExperiment

# model 0
#backbone: /remote/gpu02/ore/skatr/runs/pretraining_micro/2024-07-08_16-40-41
# model 1
backbone: /remote/gpu00/nordmann/skatr/runs/pretraining_micro/2024-07-23_15-01-12
# model 2
#backbone: /remote/gpu00/nordmann/skatr/runs/pretraining_micro/2024-07-23_15-01-30
latent_dim: 144

net:
  units:
  - ${latent_dim}
  - 64
  - 64
  - 6
  out_act: sigmoid

data:
  dir: /remote/jerry/nordmann/data_new/x5
  #dir: /scratch/ore/data_new/x5
  #dir: /scratch/nordmann/data_new/x5
  #dir: /remote/gpu01a/heneka/21cmlightcones/opt_simulations/x5
  file_by_file: False
  sequential_splits: False
  dedicated_test: True
  splits: {train: 0.015, val: 0.1, test: 0.15}

cluster:
  queue: a30
  node: 1

training:
  epochs: 120
  lr: 5.e-3
  batch_size: 64
  save_best_epoch: True
  patience: 35

freeze_backbone: True
  
defaults:
  - default
  - preprocessing: xandy_new
  - net: mlp
  - _self_