run_name: regression_${dataset.name}

experiment:
  _target_: src.experiments.RegressionExperiment

model:
  _target_: src.models.GaussianRegressor
  loss: l1
  const_sigma_frac: 0.0
  net: ${net}
  summary_net: ${summary_net}

cluster:
  queue: a30

data:
  target_indices: [0,1,2,3,4,5]

net:
  use_head: True
  out_channels: 12 # double length of target_indices

training:
  lr: 1.e-4

defaults:
  - default
  - dataset: micro
  - preprocessing: xandy
  - net: vit
  - _self_