run_name: inference_micro
experiment: InferenceExperiment

dim: 6
time_embed_dim: 32

num_test_points: 3
num_posterior_samples: 5000
sample_batch_size: 1000

net:
  units:
  - 166 # must be the sum (dim + t_embed_dim + summary_dim)
  - 256
  - 256
  - 256
  - 256
  - ${dim}

summary_net:
  out_channels: 128

solver_kwargs:
  method: midpoint
  options:
    step_size: 0.05

data:
  dir: /scratch/ore/data/x5
  file_by_file: False

training:
  epochs: 100
  lr: 0.001
  batch_size: 64
  optimizer:
    name: AdamW
    kwargs: {weight_decay: 0.001}

defaults:
  - default
  - preprocessing: xandy
  - net: mlp
  - net@summary_net: vit_micro
  - _self_