run_name: inference_micro
experiment: InferenceExperiment
plot: False

dim: 6
time_embed_dim: 32
summary_dim: 128

num_test_points: 5
num_posterior_samples: 10000
sample_batch_size: 1000

net:
  units:
  - 166 # must be the sum (dim + t_embed_dim + summary_dim)
  - 256
  - 256
  - 256
  - 256
  - ${dim}
  out_act: sigmoid

solver_kwargs:
  method: rk4
  options:
    step_size: 0.05

data:
  # not stored in gpu:
  dir: /scratch/ore/data/x5
  file_by_file: False

training:
  epochs: 100
  lr: 0.001
  batch_size: 64
  optimizer:
    name: AdamW
    kwargs: {weight_decay: 0.001}

defaults:
  - default
  - preprocessing: xandy
  - net: mlp
  - _self_