run_name: pretraining_micro:300
#run_name: debug
experiment: PretrainingExperiment
evaluate: False
plot: False

latent_dim: 128
predictor_dim: 128
ema_momentum: 0.9995
sim: l1
augment: True
mask: True
norm_target: True

net:
  out_channels: ${latent_dim}
  out_act: null
  mask_frac: 0.4
  mask_block: True

data:
  # not stored in gpu:
  dir: /remote/gpu01a/heneka/21cmlightcones/pure_simulations/x5
  # stored gpu02:
  #dir: /scratch/ore/data/x5
  file_by_file: False

training:
  epochs: 300
  lr: 0.001
  batch_size: 64
  optimizer:
    name: AdamW
    kwargs: {weight_decay: 0.001}

predictor:
  units:
    - ${latent_dim}
    - ${predictor_dim}
    - ${latent_dim}
  act: relu
  out_act: null
  drop: null

defaults:
  - default
  - preprocessing: xonly  
  - net: vit_micro
  - _self_