run_name: pretraining_${dataset.name}
evaluate: False
plot: False

experiment:
  _target_: src.experiments.PretrainingExperiment
  
model:
  _target_: src.models.JEPA
  net: ${net}
  predictor: ${predictor}
  sim: l1
  init_tgt_as_ctx: True
  momentum_schedule: False
  ema_momentum: 0.9997

net: # encoders
  use_mask_token: False
  use_head: False
  hidden_dim: 144
  depth: 4

predictor:
  _target_: src.networks.PredictorViT
  use_head: False
  hidden_dim: 48
  depth: 4
  learn_pos_encoding: False
  in_dim: ${net.hidden_dim}
  in_shape: ${net.in_shape}
  patch_shape: ${net.patch_shape}

data:
  test_frac: 0.

training:
  augment: True
  augmentations:
    - {_target_: src.utils.augmentations.RotateAndReflect, include_identity: True}
    - {_target_: src.utils.augmentations.Shift}
  epochs: 1000
  lr: 0.001
  batch_size: 64
  optimizer:
    weight_decay: 0.0

defaults:
  - default
  - dataset: micro
  - masking: multiblock
  - net: vit_micro
  - net@predictor: vit_micro
  - preprocessing: xonly  
  - _self_
