run_name: pretraining_micro
experiment: PretrainingExperiment
evaluate: False
plot: False

predictor_dim: 128
ema_momentum: 0.9997
momentum_schedule: False
sim: l1
augment: False
norm_target: False

net: # encoders
  use_mask_token: False
  use_head: False

predictor:
  use_head: False
  hidden_dim: 48
  depth: 4
  learn_pos_encoding: False
  in_dim: ${net.hidden_dim}
  in_shape: ${net.in_shape}
  patch_shape: ${net.patch_shape}

data:
  dir: /remote/gpu01a/heneka/21cmlightcones/pure_simulations/x5
  file_by_file: False

training:
  epochs: 50
  lr: 0.001
  batch_size: 64
  optimizer:
    name: AdamW
    kwargs: {weight_decay: 0.001}

defaults:
  - default
  - masking: multiblock
  - net: vit_micro
  - net@predictor: vit_micro
  - preprocessing: xonly  
  - _self_