#run_name: pretraining_micro:new_data
run_name: debug
experiment: PretrainingExperiment
evaluate: False
plot: False

latent_dim: 128
predictor_dim: 128
ema_momentum: 0.9997
momentum_schedule: False
sim: l1
augment: True
norm_target: True

net:
  out_channels: ${latent_dim}
  out_act: null

data:
  # not stored in gpu:
  #dir: /remote/gpu01a/heneka/21cmlightcones/pure_simulations/x5
  # new data
  dir: /remote/gpu00/nordmann/skatr/21cm-wrapper/data/x5
  # new data on jerry:
  # dir: /scratch/data/x5
  # stored gpu01:
  #dir: /scratch2/heneka/21cmlightcones/pure_simulations/x5
  # stored gpu02:
  #dir: /scratch/ore/data/x5
  file_by_file: True

training:
  epochs: 300
  lr: 0.001
  batch_size: 64
  optimizer:
    name: AdamW
    kwargs: {weight_decay: 0.001}

predictor:
  units:
    - ${latent_dim}
    - ${predictor_dim}
    - ${latent_dim}
  act: relu
  out_act: null
  drop: null

defaults:
  - default
  - masking: context_target
  - net: vit_micro
  - preprocessing: xonly  
  - _self_