run_name: pretraining_mini
experiment: PretrainingExperiment
evaluate: False
plot: False

latent_dim: 128
predictor_dim: 128
ema_momentum: 0.9997
momentum_schedule: False
sim: l1
augment: True
norm_target: True

net:
  out_channels: ${latent_dim}
  out_act: null

data:
# old data on gpu02
  #dir: /scratch/ore/data/x2
# new data on h100
  dir: /scratch/nordmann/data_new/x2
  file_by_file: False
  dedicated_test: True

training:
  epochs: 50
  lr: 0.001
  batch_size: 16
  optimizer:
    name: AdamW
    kwargs: {weight_decay: 0.001}

predictor:
  units:
    - ${latent_dim}
    - ${predictor_dim}
    - ${latent_dim}
  act: relu
  out_act: null
  drop: null

defaults:
  - default
  - masking: block
  - net: vit_mini
  - preprocessing: xonly  
  - _self_