run_name: regression_mini_${net.arch}
experiment: RegressionExperiment

data:
  dir: /scratch/ore/data/x2
  file_by_file: True

training:
  epochs: 120
  lr: 1.e-4
  batch_size: 64
  
defaults:
  - default
  - preprocessing: xandy
  - net: vit_mini
  - _self_