run_name: regression_micro_${net.arch}
experiment: RegressionExperiment

data:
  dir: /scratch/ore/data/x5
  file_by_file: False

  training:
  batch_size: 64
  epochs: 300
  
defaults:
  - default
  - preprocessing: xandy
  - net: vit_micro
  - _self_