run_name: regression_${net.arch}
experiment: RegressionExperiment
data:
  dir: /remote/gpu01a/heneka/21cmlightcones/pure_simulations
  # dir: /scratch2/heneka/21cmlightcones/pure_simulations
  file_by_file: True

defaults:
  - default
  - preprocessing: xandy  
  - net: vit
  - _self_