run_name: regression:conv:batch32
experiment: RegressionExperiment
data:
  dir: /remote/gpu01a/heneka/21cmlightcones/pure_simulations
  #dir: /scratch2/heneka/21cmlightcones/pure_simulations
  file_by_file: True

preprocessing:
  AddSingletonChannel: {}
  Center: {}

training:
  epochs: 120
  lr: 0.0001
  batch_size: 32
  
defaults:
  - default
  - net: vit
  - _self_