run_name: regression_mini_${net.arch}
experiment: RegressionExperiment

data:
  dir: /scratch/ore/data/x2
  file_by_file: False
  
defaults:
  - default
  - preprocessing: xandy
  - net: vit_mini
  - _self_