run_name: regression_${net}
experiment: RegressionExperiment
data:
  dir: /remote/gpu01a/heneka/21cmlightcones/pure_simulations/x2
  # dir: /scratch2/heneka/21cmlightcones/pure_simulations/x2
  file_by_file: False

preprocessing:
  AddSingletonChannel: {}
  Center: {}
  
defaults:
  - default
  - net: cnn_mini
  - _self_