run_name: regression_micro_new_${net.arch}
target_indices: [1,3,2,4,5]

data:
  dir: /scratch/ore/data_new/x5
  
net:
  out_channels: 5 # length of target_indices

defaults:
  - regression_micro
  - _self_