run_name: regression_${dataset.name}

experiment:
  _target_: src.experiments.RegressionExperiment

model:
  _target_: src.models.Regressor
  loss: l1
  net: ${net}
  summary_net: ${summary_net}

cluster:
  queue: a30

data:
  target_indices: [0,1,2,3,4,5]

net:
  out_channels: 6 # length of target_indices

training:
  lr: 1.e-4

defaults:
  - default
  - dataset: micro
  - preprocessing: xandy
  - net: vit
  - _self_