run_name: regression_${net.arch}
experiment: RegressionExperiment

target_indices: [0,1,2,3,4,5]
loss: l1
gaussian: False

data_shape: [140, 140, 2350]

cluster:
  queue: h100
  
data:
  dir: /scratch/ore/data/hr/half
  file_by_file: True
  
net:
  use_head: True
  out_channels: 6 # length of target_indices

training:
  lr: 1.e-4

defaults:
  - default
  - preprocessing: xandy
  - net: vit
  - _self_