#run_name: regression_micro_H${net.hidden_dim}:D${net.depth}:Hs${net.num_heads} #:drop${net.proj_drop}:out_mlp #:big_zpatch
run_name: regression_micro:H${net.hidden_dim}:zpatch=10
experiment: RegressionExperiment
data:
  # not stored in gpu:
  # also use cluster.node=1 (no preferred gpu)
  dir: /remote/gpu01a/heneka/21cmlightcones/pure_simulations/x5
  # stored gpu01:
  #dir: /scratch2/heneka/21cmlightcones/pure_simulations/x5
  # stored gpu02:
  #dir: /scratch/ore/data/x5
  # in pbs.yaml node: gpu02
  # increasingly worse with growing epochs
  # optional data
  #dir: /remote/gpu01a/heneka/21cmlightcones/opt_simulations/x5
  file_by_file: True


preprocessing:
  AddSingletonChannel: {}
  Center: {}

training:
  epochs: 120
  lr: 1.e-4
  batch_size: 32
  
defaults:
  - default
  - preprocessing: xandy
  - net: vit_micro
  - _self_