run_name: regression_${net.arch}
experiment: RegressionExperiment
data:
  not stored in gpu:
  # also use cluster.node=1 (no preferred gpu)
  #dir: /remote/gpu01a/heneka/21cmlightcones/pure_simulations/x2
  # stored gpu01:
  dir: /scratch2/heneka/21cmlightcones/pure_simulations/x2
  # stored gpu02:
  # dir: /scratch/ore/data/x2
  # in pbs.yaml node: gpu01
  # increasingly worse with growing epochs
  file_by_file: False

preprocessing:
  AddSingletonChannel: {}
  Center: {}

training:
  # seemed converge at 10
  epochs: 200
  # standard 1.e-3
  lr: 1.e-3
  
defaults:
  - default
  - net: vit_mini
  - _self_