#run_name: regression_mini_${net.arch}_P${net.patchx}x${net.patchz}:H${net.hidden_dim}:D${net.depth}:Hs${net.num_heads}
run_name: regression_micro_${net.arch}_H${net.hidden_dim}:D${net.depth}:Hs${net.num_heads} #:drop${net.proj_drop}:out_mlp #:big_zpatch
experiment: RegressionExperiment
data:
  # not stored in gpu:
  # also use cluster.node=1 (no preferred gpu)
  #dir: /remote/gpu01a/heneka/21cmlightcones/pure_simulations/x5
  #stored gpu01:
  dir: /scratch2/heneka/21cmlightcones/pure_simulations/x5
  # stored gpu02:
  #dir: /scratch/ore/data/x5
  # in pbs.yaml node: gpu02
  # increasingly worse with growing epochs
  file_by_file: False


preprocessing:
  AddSingletonChannel: {}
  Center: {}

training:
  epochs: 120
  lr: 1.e-4
  batch_size: 32
  
defaults:
  - default
  - net: vit_micro
  - _self_